version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/init.sql

  express-backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres